# Generated by Django 5.2 on 2025-04-06 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('submitted_file', models.FileField(upload_to='submitted_files/')),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('benchmark_ready', models.CharField(default='Not Ready', max_length=255)),
                ('benchmark_date', models.DateField(blank=True, default=None, null=True)),
                ('benchmark_version', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('plot1', models.ImageField(blank=True, default=None, null=True, upload_to='plots/')),
                ('plot2', models.ImageField(blank=True, default=None, null=True, upload_to='plots/')),
                ('plot3', models.ImageField(blank=True, default=None, null=True, upload_to='plots/')),
                ('plot4', models.ImageField(blank=True, default=None, null=True, upload_to='plots/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
